import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NavBar from "@/components/layout/NavBar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900 bg-gray-50`}
      >
        <div className="grid grid-cols-[250px_1fr] grid-rows-[64px_1fr] h-screen w-full overflow-hidden">
          <div className="col-start-1 row-span-2 bg-white border-r border-gray-200 z-10">
            <SideBar />
          </div>

          <div className="col-start-2 row-start-1 bg-white border-b border-gray-200 z-10 w-full h-full">
            <NavBar />
          </div>

          <main className="col-start-2 row-start-2 overflow-y-auto p-8 relative">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
